### ISSUE TITLE
"Unknow file extension" error when running an empty project with Node 18.1.0

### ISSUE THREAD

**Issue by QuentinWidlocher** [tmountain/pico-8-typescript#1]
I use node 18.1.0 and I tried this tool by creating a sample project by running these commands :

```bash
./bin/tspico8.js init -d test-project
./bin/tspico8.js run -d ./test-project/
```

After Typescript is done compiling and uglify is done compressing, when `./node_modules/.bin/jspicl-cli` is ran, it just hangs there so I ran the jspicl-cli command manually and this is what I got :

```
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/Quentin/Documents/Projects/Native/Pico8/pico-8-typescript/node_modules/.pnpm/jspicl-cli@0.4.0/node_modules/jspicl-cli/bin/cli. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file /Users/Quentin/Documents/Projects/Native/Pico8/pico-8-typescript/node_modules/.pnpm/jspicl-cli@0.4.0/node_modules/jspicl-cli/package.json caused this "type":"module" context. Try changing /Users/Quentin/Documents/Projects/Native/Pico8/pico-8-typescript/node_modules/.pnpm/jspicl-cli@0.4.0/node_modules/jspicl-cli/bin/cli to have a file extension. Note the "bin" field of package.json can point to a file with an extension, for example {"type":"module","bin":{"cli":"./bin/cli.js"}}
    at new NodeError (node:internal/errors:377:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at ESMLoader.load (node:internal/modules/esm/loader:431:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at #createModuleJob (node:internal/modules/esm/loader:369:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v18.1.0
```

I managed to get the tool working by renaming `./node_modules/jspicl-cli/bin/cli` to `cli.cjs` and `./node_modules/jspicl-cli/bin/plugin` to `plugin.cjs`.

I also needed to change the paths in `cli.cjs` and `./node_modules/.bin/jspicl-cli` of course.

**Comment by QuentinWidlocher** [comment]
Looks like this issue exists already here since nearly two years 😕

https://github.com/jspicl/jspicl-cli/issues/5

@tmountain what node version do you use to not have this problem ?

**Comment by tmountain** [comment]
I included a patch in the repo which is intended to address this issue.

```
$ cat patches/jspicl-cli+0.4.0.patch 
diff --git a/node_modules/jspicl-cli/package.json b/node_modules/jspicl-cli/package.json
index 227b4f4..6672686 100644
--- a/node_modules/jspicl-cli/package.json
+++ b/node_modules/jspicl-cli/package.json
@@ -77,6 +79,5 @@
     "start": "rollup -c",
     "test": "NODE_ENV=test NODE_PATH=src mocha"
   },
-  "type": "module",
   "version": "0.4.0"
 }
```


```
$ npm install

> pico-8-typescript@0.1.0 postinstall /private/tmp/pico-8-typescript
> patch-package

patch-package 6.4.7
Applying patches...
jspicl-cli@0.4.0 ✔
```

I'm using node v12.22.11, and this happens automatically as a post-install step.

This said, it looks like jspicl-cli is abandoned, so maybe it makes more sense to just fork it and apply the fix. I'm open to suggestions. Thanks for checking out the project and reporting the issue.

**Comment by QuentinWidlocher** [comment]
Yes sorry, I saw your patch just now. It's still weird that removing the `"type": "module"` just doesn't work with node 18.

I'm working on a quick fix to update jspicl-cli, maybe I'll make a fork later as you said.

**Comment by tmountain** [comment]
Ah, okay, so that patch doesn't work with node 18... If you can tell me what you need to do to resolve the issue, I can make sure I'm handling it appropriately. Thanks.

**Comment by QuentinWidlocher** [comment]
In my first message I told you everything I changed but I'll put the changes here so it's easier.

<details>
<summary>node_modules/.bin/jspicl-cli</summary>

```bash
 if [ -x "$basedir/node" ]; then
+  exec "$basedir/node"  "$basedir/../jspicl-cli/bin/cli.cjs" "$@"
else
  exec node  "$basedir/../jspicl-cli/bin/cli.cjs" "$@"
fi
```

</details>

Also, after succeeding in running the tool, I created a class in ts and everything broke.  
I changed another thing in `jspicl-cli` to fix it, do you want me t make another issue to explain this maybe ?

**Comment by tmountain** [comment]
Yes, please. Thank you.

**Comment by QuentinWidlocher** [comment]
In my first message I told you everything I changed but I'll put the changes here so it's easier.

<details>
<summary>Files to rename</summary>

```diff
- node_modules/jspicl-cli/bin/cli
+ node_modules/jspicl-cli/bin/cli.cjs

- node_modules/jspicl-cli/bin/plugin.js
+ node_modules/jspicl-cli/bin/plugin.cjs
```

</details>

<details>
<summary>node_modules/.bin/jspicl-cli</summary>

```diff
if [ -x "$basedir/node" ]; then
-  exec "$basedir/node"  "$basedir/../jspicl-cli/bin/cli" "$@"
+  exec "$basedir/node"  "$basedir/../jspicl-cli/bin/cli.cjs" "$@"
else
-   exec node  "$basedir/../jspicl-cli/bin/cli" "$@"
+   exec node  "$basedir/../jspicl-cli/bin/cli.cjs" "$@"
fi
```

</details>

<details>
<summary>node_modules/jspicl-cli/bin/cli.cjs</summary>

```diff
const yargs = require("yargs");
const rollup = require("rollup");
- const jspiclPlugin = require("./plugin.js");
+ const jspiclPlugin = require("./plugin.cjs");

const options = {
```

</details>

Also, after succeeding running the tool, I created a class in ts and everything broke.  
I changed another thing in `jspicl-cli` to fix it, do you want me to make another issue to explain this maybe (if you want to patch this change too, or to discuss a potential fork) ?

**Comment by tmountain** [comment]
Sorry, my reply was out of sequence, yes I would appreciate it if you created an issue regarding creating a class breaking TS. If you have a fix for that, please share the details.

Ideally, a fork of jspicl-cli would be NPM packaged (and scoped) for easy consumption. I can take your changes and do that sometime soon, or if you do it and share the package, I can point to it. Either way is fine.
